### ISSUE TITLE
Seems that await * not supported by regenerator

### ISSUE THREAD

**Issue by cgcgbcbc** [tc39/proposal-async-await#85]
`regenerator -r server.asyncawait.js` gives output

```
Error while reading module server.asyncawait:
Error: Line 31: Unexpected token *
    at throwError (/usr/local/lib/node_modules/regenerator/node_modules/esprima-fb/esprima.js:2819:21)
    at throwUnexpected (/usr/local/lib/node_modules/regenerator/node_modules/esprima-fb/esprima.js:2881:9)
    at parsePrimaryExpression (/usr/local/lib/node_modules/regenerator/node_modules/esprima-fb/esprima.js:3593:9)
    at parseLeftHandSideExpressionAllowCall (/usr/local/lib/node_modules/regenerator/node_modules/esprima-fb/esprima.js:3683:61)
    at parsePostfixExpression (/usr/local/lib/node_modules/regenerator/node_modules/esprima-fb/esprima.js:3723:20)
    at parseUnaryExpression (/usr/local/lib/node_modules/regenerator/node_modules/esprima-fb/esprima.js:3790:16)
    at parseBinaryExpression (/usr/local/lib/node_modules/regenerator/node_modules/esprima-fb/esprima.js:3880:16)
    at parseConditionalExpression (/usr/local/lib/node_modules/regenerator/node_modules/esprima-fb/esprima.js:3940:16)
    at parseAssignmentExpression (/usr/local/lib/node_modules/regenerator/node_modules/esprima-fb/esprima.js:4193:16)
    at parseAwaitExpression (/usr/local/lib/node_modules/regenerator/node_modules/esprima-fb/esprima.js:6125:16)
From previous event:
    at buildP (/usr/local/lib/node_modules/regenerator/node_modules/commoner/lib/reader.js:167:16)
    at Object.ModuleReader.processOutputP (/usr/local/lib/node_modules/regenerator/node_modules/commoner/lib/reader.js:221:16)
    at Object.ModuleReader.buildModuleP (/usr/local/lib/node_modules/regenerator/node_modules/commoner/lib/reader.js:132:23)
    at Object.wrapper [as buildModuleP] (/usr/local/lib/node_modules/regenerator/node_modules/commoner/lib/util.js:53:31)
    at /usr/local/lib/node_modules/regenerator/node_modules/commoner/lib/reader.js:126:27
Error: Line 31: Unexpected token *
    at throwError (/usr/local/lib/node_modules/regenerator/node_modules/esprima-fb/esprima.js:2819:21)
    at throwUnexpected (/usr/local/lib/node_modules/regenerator/node_modules/esprima-fb/esprima.js:2881:9)
    at parsePrimaryExpression (/usr/local/lib/node_modules/regenerator/node_modules/esprima-fb/esprima.js:3593:9)
    at parseLeftHandSideExpressionAllowCall (/usr/local/lib/node_modules/regenerator/node_modules/esprima-fb/esprima.js:3683:61)
    at parsePostfixExpression (/usr/local/lib/node_modules/regenerator/node_modules/esprima-fb/esprima.js:3723:20)
    at parseUnaryExpression (/usr/local/lib/node_modules/regenerator/node_modules/esprima-fb/esprima.js:3790:16)
    at parseBinaryExpression (/usr/local/lib/node_modules/regenerator/node_modules/esprima-fb/esprima.js:3880:16)
    at parseConditionalExpression (/usr/local/lib/node_modules/regenerator/node_modules/esprima-fb/esprima.js:3940:16)
    at parseAssignmentExpression (/usr/local/lib/node_modules/regenerator/node_modules/esprima-fb/esprima.js:4193:16)
    at parseAwaitExpression (/usr/local/lib/node_modules/regenerator/node_modules/esprima-fb/esprima.js:6125:16)
From previous event:
    at buildP (/usr/local/lib/node_modules/regenerator/node_modules/commoner/lib/reader.js:167:16)
    at Object.ModuleReader.processOutputP (/usr/local/lib/node_modules/regenerator/node_modules/commoner/lib/reader.js:221:16)
    at Object.ModuleReader.buildModuleP (/usr/local/lib/node_modules/regenerator/node_modules/commoner/lib/reader.js:132:23)
    at Object.wrapper [as buildModuleP] (/usr/local/lib/node_modules/regenerator/node_modules/commoner/lib/util.js:53:31)
    at /usr/local/lib/node_modules/regenerator/node_modules/commoner/lib/reader.js:126:27
```

Version information

```
$ regenerator --version
0.8.42
$ node --version
v5.4.0
```

**Comment by inikulin** [comment]
> Seems that await \* not supported by regenerator

Well, I suppose you should open an issue in [Regenerator repo](https://github.com/facebook/regenerator) then.

P.s. `await*` was removed from the spec. Use `Promise.all` instead.

**Comment by cgcgbcbc** [comment]
It seems that regenerator's parser does not support `await *` syntax, so maybe the code should be modified or use babel instead of regenerator?

https://github.com/facebook/regenerator/issues/201

**Comment by andrenatal** [comment]
I'm experiencing the same issue.

**Comment by inikulin** [comment]
@cgcgbcbc @andrenatal Guys, `await*` is no more in the spec and it's not a valid ES syntax anymore. Instead of

``` js
await * arrayOfPromises
```

use 

``` js
await Promise.all(arrayOfPromises);
```

Anyway, this repo is dedicated to the `async/await` specification and not the actual implementations like Regenerator. So, please report issues to the appropriate place.

**Comment by cgcgbcbc** [comment]
@inikulin 
It seems that this line https://github.com/tc39/ecmascript-asyncawait/blob/master/server.asyncawait.js#L31
should be modified for the newest spec?
Anyway, after that modification, it seems that the sample code no longer worked at all ( Maybe due to github api's change). So I suggest removing these lines in Readme https://github.com/tc39/ecmascript-asyncawait/blame/master/README.md#L7-L13 in case that beginners like me and @andrenatal will get stuck here.

**Comment by inikulin** [comment]
@cgcgbcbc My bad, I didn't get that you are talking about example from this repo. You are completely right, it would be nice to update the README and example, I assume that PRs are welcome =).

**Comment by zenparsing** [comment]
Can we close this issue?

**Comment by bterlson** [comment]
Gah sorry :(
